name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le déploiement uniquement sur les push vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Version de Node.js (peut être ajustée selon tes besoins)

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token GitHub pour déployer
        publish_dir: ./build  # Répertoire de build généré par React
